### ISSUE TITLE
GetMulti fails in Cloud Datastore

### ISSUE THREAD

**Issue by sinmetal** [mercari/datastore#74]
Attempting to receive data in a struct with GetMulti will fail.

## error message

```
datastore: dst has invalid type
```

## try code sample

```
type Hoge struct {
	ID   string `datastore:"-"`
	Body string
}

var rvs []*Hoge
if err := ds.GetMulti(ctx, keys, &rvs); err != nil {
    t.Fatal(err)
}
```

try code https://github.com/sinmetal/dstest/blob/master/ds_test.go#L47

**Comment by sinmetal** [comment]
I found working code

```
rvs := make([]*Hoge, len(keys))
if err := ds.GetMulti(ctx, keys, rvs); err != nil {
	t.Fatal(err)
}
```

**Comment by vvakame** [comment]
I'll check this code is same behavior as original cloud datastore library.

**Comment by vvakame** [comment]
confirmed. This is not an issue. thanks to reporting!
