### ISSUE TITLE
Support `in` , `not-in` , and `!=` query operators

### ISSUE THREAD

**Issue by s-takehana** [mercari/datastore#97]
`in` , `not-in` , and `!=` query operators are new features introduced in `cloud.google.com/go/datastore` `v1.8.0`.

https://github.com/googleapis/google-cloud-go/blob/main/datastore/CHANGES.md#180-2022-06-21

`Query.Filter` is deprecated.
https://pkg.go.dev/cloud.google.com/go/datastore#Query.Filter

I want to use the query operators via `boom`.

**Comment by s-takehana** [comment]
https://cloud.google.com/datastore/docs/concepts/queries#not-equal

> Note: This features is available for Firestore in Datastore mode. It is not available for pre-migration [Datastore databases](https://cloud.google.com/datastore/docs/upgrade-to-firestore).

https://cloud.google.com/sdk/gcloud/reference/beta/emulators/datastore/start

> --use-firestore-in-datastore-mode
Runs the emulator in Cloud Firestore in Datastore Mode. Reads are always strongly consistent and --consistency flag may not be specified.

**Comment by vvakame** [comment]
@s-takehana thanks to request. I just published `v2.2.0`. PTAL 🙏

**Comment by s-takehana** [comment]
@vvakame Thank you!
